# This is a basic workflow to help you get started with Actions

name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Adjust based on your project requirements
      - name: Install package.json
        run: npm init -y

      # 3. Show the package.json file (for debugging)
      - name: Show package.json
        run: cat package.json

      # 4. Install dependencies
      - name: Install Dependencies
        run: npm install

      # 5. Run tests
      - name: Run Tests
        run: npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: success() # Only deploy if the test job passes
    steps:
      # 1. Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Deployment Step
      - name: Deploy to Staging
        run: echo "Deploying to staging pipeline..."
      # Add actual deployment commands here


